#Libraries necessary for execution of all scripts in MSc thesis
#on differential enhancer usage in MM
library(tidyverse)
library(readxl)
library(ggridges)
library(ggpubr)
library(RColorBrewer)
library(ggrepel)
library(reshape2)
library(gplots)
library(tidyr)
library(scales)
library(tidyverse)
library(GenomicRanges)
library(plotrix)
library(wesanderson)
library(eulerr)
library(heatmap3)
library(preprocessCore)
library(limma)
library(scales)
library(ggfortify)