This script is for TF binding analysis (IRF4) in MM cell lines and creates plots for data visualisation. Initial analysis contained a mistake with promoter definitions so initial enhancer lists are first adjusted.
```{r}
#Loading necessary libraries 
source("~/MM_thesis_repo/libraries_thesis.R")
source("~/MM_thesis_repo/functions_MM.R")
```

```{r}
chr_list <- c(paste0("chr", seq(from=1, to=22)), "chrX", "chrY")
```

```{r}
enhancers_list_old <- read_tsv("~/myeloma_thesis_R/TF/IRF4/cell_lines_enhancer_tag_annot.txt") %>%
  select(c(-strand, -`Total subpeaks`))
EJM <- read_tsv("~/myeloma_thesis_R/TF/IRF4/EJM_IRF4.txt", skip = 39) %>%
  select(c(1:4)) %>%
  filter(chr %in% chr_list) %>%
  set_names(c("PeakID", "chr", "start", "end")) 
H929 <- read_tsv("~/myeloma_thesis_R/TF/IRF4/H929_IRF4.txt", skip = 39) %>%
  select(c(1:4)) %>%
  filter(chr %in% chr_list) %>%
  set_names(c("PeakID", "chr", "start", "end")) 
MM1S <- read_tsv("~/myeloma_thesis_R/TF/IRF4/MM1S_IRF4.txt", skip = 39) %>%
  select(c(1:4)) %>%
  filter(chr %in% chr_list) %>%
  set_names(c("PeakID", "chr", "start", "end")) 
KMS12 <- read_tsv("~/myeloma_thesis_R/TF/IRF4/KMS12_IRF4_peaks.txt", skip = 39) %>%
  select(c(1:4)) %>%
  filter(chr %in% chr_list) %>%
  set_names(c("PeakID", "chr", "start", "end")) 
IRF4_merged <- read_tsv("~/myeloma_thesis_R/TF/IRF4/IRF_merged.txt") %>%
  select(c(-strand, -Stat, -`Total subpeaks`))
IRF4_merged_venn <- read_tsv("~/myeloma_thesis_R/TF/IRF4/IRF4_merged_venn.txt")
```

```{r}
#Fixing the list of enhancers based on the new approach where promoters are excluded 
gene_list <- read_tsv("~/myeloma_thesis_R/general_data/hg38_refseq_genelist.txt", col_names = TRUE)
chr_list <- c(paste0("chr", seq(from=1, to=22)), "chrX", "chrY")

gene_list_promoters <- gene_list %>%
  filter(chrom %in% chr_list) %>%
  select(c(chrom, strand, txStart, txEnd, name2)) %>%
  mutate(txStart = ifelse(strand == "-", txEnd, txStart)) %>%
  select(c(chrom, txStart, name2)) %>%
  unique() %>%
  set_names("chr", "start", "Geneid") %>%
  mutate(end = start +1) %>%
  select(3,1,2,4) %>%
  mutate(promoter.start = start - 2000) %>%
  mutate(promoter.end = start + 2000)

promoters_coordinates <- gene_list_promoters %>%
  select(Geneid, chr, promoter.start, promoter.end) %>%
  set_names(c("Promoter", "chr", "start", "end"))

enhancers_list <-  setdiff(GRanges(enhancers_list_old), GRanges(promoters_coordinates), ignore.strand = TRUE) %>%
  as.data.frame() %>%
  mutate(EnhancerID = paste0("EnhancerID", row.names(.))) %>% 
  filter(width > 250) %>%
  select(6,1:3) %>%
  set_names(c("EnhancerID", "chr", "start", "end")) 

overlap_old_new <- findOverlaps(query=GRanges(enhancers_list), subject=GRanges(enhancers_list_old)) %>%
         as.data.frame()

enhancers_list <- enhancers_list %>%
  mutate(queryHits = as.numeric(row.names(.))) %>%
  full_join(overlap_old_new, by="queryHits") %>%
  left_join(enhancers_list_old %>%
              select(-chr, -start, -end, -PeakID) %>%
              mutate(subjectHits = as.numeric(row.names(.))), 
            by = "subjectHits") %>%
    select(-subjectHits, -queryHits)
  
```

```{r}
#Create a venn diagram to show overlap between cell lines
venn <- euler(c(
  "MM1S" = 13273, 
  "KMS12" = 1749, 
  "KMS12&MM1S" = 1137, 
  "H929" = 8358, 
  "H929&MM1S" = 5642,
  "H929&KMS12" = 524, 
  "H929&MM1S&KMS12" = 1362, 
  "EJM" = 2201, 
  "EJM&MM1S" = 1197, 
  "EJM&KMS12" = 132, 
  "EJM&KMS12&MM1S" = 327, 
  "EJM&H929" = 992, 
  "EJM&H929&MM1S" = 2245,
  "EJM&H929&KMS12" = 244, 
  "EJM&H929&KMS12&MM1S" = 2294
))

venn_plot <- plot(venn, 
    quantities = TRUE
     )
venn_plot
```

```{r}
#Find overlaps between enhancers and IRF4 binding sites
overlap_enhancers <- findOverlaps(query=GRanges(IRF4_merged), subject=GRanges(enhancers_list)) %>%
         as.data.frame()

enhancers_IRF4 <- IRF4_merged %>%
  mutate(queryHits = as.numeric(row.names(.))) %>%
  full_join(overlap_enhancers, by="queryHits") %>%
  full_join(enhancers_list %>%
              mutate(subjectHits = as.numeric(row.names(.))), 
            by = "subjectHits", suffix = c(".IRF4", ".enhancer")) %>%
    select(-queryHits, -subjectHits) %>%
   mutate(enhancer_type = ifelse(
     is.na(EnhancerID), "no enhancer", enhancer_type
   )) %>%
  #select(-c(chr.IRF4, -start.IRF4, -end.IRF4, PeakID)) %>%
  mutate(IRF4_MM1S = 
           ifelse(
             !is.na(`MM1S_IRF4_forhomer.txt`), "yes", "no"
           )) %>%
  mutate(IRF4_H929 = 
           ifelse(
             !is.na(`H929_IRF4_forhomer.txt`), "yes", "no"
           )) %>%
  mutate(IRF4_EJM = 
           ifelse(
             !is.na(`EJM_IRF4_forhomer.txt`), "yes", "no"
           )) %>%
  mutate(IRF4_KMS12 = 
           ifelse(
             !is.na(`KMS12_IRF4_forhomer.txt`), "yes", "no"
           )) %>%
  select(-EJM_IRF4_forhomer.txt, -H929_IRF4_forhomer.txt, -KMS12_IRF4_forhomer.txt, -MM1S_IRF4_forhomer.txt) 

enhancers_IRF_tosave <- enhancers_IRF4 %>%
  select(1:4, 6:9, 21:25)
```

```{r}
IRF4_summarised <- enhancers_IRF4 %>%
  select(enhancer_type, IRF4_MM1S, IRF4_EJM, IRF4_H929, IRF4_KMS12) %>%
  melt(id = "enhancer_type", variable = "cell_line", value.name = "IRF4_binding") %>%
  group_by(cell_line, enhancer_type, IRF4_binding) %>%
  summarise(n = n())
```

```{r}
barchart <- IRF4_summarised %>%
  filter(cell_line == "IRF4_H929") %>%
  ggplot(aes(x = enhancer_type, y = n, fill = IRF4_binding)) +
  # facet_grid(.~cell_line) +
  geom_bar(stat = "identity")
barchart2

barchart3 <- IRF4_summarised %>%
  filter(enhancer_type %in% c("H929", "MM1S", "KMS12", "EJM")) %>%
  ggplot(aes(x = enhancer_type, y = n, fill = IRF4_binding)) +
  facet_grid(.~cell_line) +
  geom_bar(stat = "identity")
barchart3
```

```{r}
IRF4_proportion <- IRF4_summarised %>%
  group_by(enhancer_type) %>%
  summarise(total = sum(n)/4) %>%
  left_join(IRF4_summarised, by = "enhancer_type") %>%
  mutate(proportion = n/total)
```

```{r}
barchart4 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_H929") %>%
  ggplot(aes(x = enhancer_type, y = proportion, fill = IRF4_binding)) +
  # facet_grid(.~cell_line) +
  geom_bar(stat = "identity")
barchart4

barchart5 <- IRF4_proportion %>%
  filter(enhancer_type %in% c("H929", "MM1S", "KMS12", "EJM")) %>%
  ggplot(aes(x = enhancer_type, y = proportion, fill = IRF4_binding)) +
  facet_grid(.~cell_line) +
  geom_bar(stat = "identity")
barchart5
```


```{r}
#Barchart comparing the binding of IRF4 in each cell line at cell line specific enhancers and other loci

#MM1S data
MM1S_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_MM1S") %>%
  mutate(category = ifelse(enhancer_type == "MM1S", "MM1S", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
MM1S_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_MM1S") %>%
  mutate(category = ifelse((enhancer_type == "MM1S" & cell_line == "IRF4_MM1S"), "MM1S", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
MM1S_IRF4_binding <- MM1S_IRF4_binding_1 %>%
  bind_cols(MM1S_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "MM1S")

#H929 data
H929_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_H929") %>%
  mutate(category = ifelse(enhancer_type == "H929", "H929", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
H929_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_H929") %>%
  mutate(category = ifelse((enhancer_type == "H929" & cell_line == "IRF4_H929"), "H929", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
H929_IRF4_binding <- H929_IRF4_binding_1 %>%
  bind_cols(H929_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "H929")

#KMS12 data
KMS12_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_KMS12") %>%
  mutate(category = ifelse(enhancer_type == "KMS12", "KMS12", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
KMS12_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_KMS12") %>%
  mutate(category = ifelse(enhancer_type == "KMS12", "KMS12", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
KMS12_IRF4_binding <- KMS12_IRF4_binding_1 %>%
  bind_cols(KMS12_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "KMS12")

#EJM data
EJM_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_EJM") %>%
  mutate(category = ifelse(enhancer_type == "EJM", "EJM", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
EJM_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_EJM") %>%
  mutate(category = ifelse(enhancer_type == "EJM", "EJM", "other")) %>%
  group_by(category, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
EJM_IRF4_binding <- EJM_IRF4_binding_1 %>%
  bind_cols(EJM_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "EJM")

#Join the sub datasets together
data_for_barchart <- MM1S_IRF4_binding %>%
  bind_rows(H929_IRF4_binding, KMS12_IRF4_binding, EJM_IRF4_binding)

trial <- MM1S_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "MM1S cell line", y = "Proportion", fill = "IRF4 binding") +
  scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  scale_x_discrete(labels=c("unique enhancers", "other loci")) +
  main_theme() +
  coord_fixed(ratio = 1.5) 


trial2 <- H929_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "H929 cell line", y = "Proportion", fill = "IRF4 binding") +
    scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  scale_x_discrete(labels=c("unique enhancers", "other loci")) +
  main_theme()+
  coord_fixed(ratio = 1.5) 


trial3 <- KMS12_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "KMS12 cell line", y = "Proportion", fill = "IRF4 binding") +
  scale_x_discrete(labels=c("unique enhancers", "other loci")) +
  scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  main_theme() +
  coord_fixed(ratio = 1.5) 

trial4 <- EJM_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "EJM cell line", y = "Proportion", fill = "IRF4 binding") +
  scale_x_discrete(labels=c("unique enhancers", "other loci")) +
  scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  main_theme() +
  coord_fixed(ratio = 1.5) 


final_barchart <- ggpubr::ggarrange(trial, trial2, trial3, trial4,
                  common.legend = T, # COMMON LEGEND
                  legend = "right", # Align them both, horizontal and vertical
                  nrow = 2, ncol =2) 
  

barchart6 <- data_for_barchart %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(stat = "identity") +
  facet_wrap(~cell_line) +
  coord_fixed(ratio = 4) 

barchart6
```

```{r}
#Barchart comparing the binding of IRF4 in each cell line at cell line specific enhancers and other groups
#MM1S data
MM1S_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_MM1S") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse(enhancer_type == "MM1S", "MM1S", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
MM1S_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_MM1S") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse((enhancer_type == "MM1S" & cell_line == "IRF4_MM1S"), "MM1S", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
MM1S_IRF4_binding <- MM1S_IRF4_binding_1 %>%
  bind_cols(MM1S_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "MM1S")

#H929 data
H929_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_H929") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse(enhancer_type == "H929", "H929", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
H929_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_H929") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
 # mutate(category = ifelse((enhancer_type == "H929" & cell_line == "IRF4_H929"), "H929", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
H929_IRF4_binding <- H929_IRF4_binding_1 %>%
  bind_cols(H929_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "H929")

#KMS12 data
KMS12_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_KMS12") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse(enhancer_type == "KMS12", "KMS12", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
KMS12_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_KMS12") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse(enhancer_type == "KMS12", "KMS12", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
KMS12_IRF4_binding <- KMS12_IRF4_binding_1 %>%
  bind_cols(KMS12_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "KMS12")

#EJM data
EJM_IRF4_binding_1 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_EJM") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse(enhancer_type == "EJM", "EJM", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_total = sum(total)) 
EJM_IRF4_binding_2 <- IRF4_proportion %>%
  filter(cell_line == "IRF4_EJM") %>%
  filter(enhancer_type != "no enhancer" & enhancer_type != "other peak") %>%
  #mutate(category = ifelse(enhancer_type == "EJM", "EJM", "other")) %>%
  group_by(enhancer_type, IRF4_binding) %>%
  summarise(new_n = sum(n)) 
EJM_IRF4_binding <- EJM_IRF4_binding_1 %>%
  bind_cols(EJM_IRF4_binding_2) %>%
  select(1:3,6) %>%
  set_names(c("category", "IRF4_binding", "total", "n")) %>%
  mutate(proportion = n/total) %>%
  mutate(cell_line = "EJM")


data_for_barchart <- MM1S_IRF4_binding %>%
  bind_rows(H929_IRF4_binding, KMS12_IRF4_binding, EJM_IRF4_binding)
```

```{r}
trial <- MM1S_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "MM1S cell line", y = "Proportion", fill = "IRF4 binding") +
  scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  scale_x_discrete(labels=c("common", "EJM", "H929", "KMS12", "MM1S"), guide = guide_axis(angle = 45)) +
  main_theme() +
  coord_fixed(ratio = 3) 


trial2 <- H929_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "H929 cell line", y = "Proportion", fill = "IRF4 binding") +
    scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  scale_x_discrete(labels=c("common", "EJM", "H929", "KMS12", "MM1S"), guide = guide_axis(angle = 45)) +
  main_theme() +
  coord_fixed(ratio = 3) 


trial3 <- KMS12_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "KMS12 cell line", y = "Proportion", fill = "IRF4 binding") +
  scale_x_discrete(labels=c("common", "EJM", "H929", "KMS12", "MM1S"), guide = guide_axis(angle = 45)) +
  scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  main_theme() +
  coord_fixed(ratio = 3) 

trial4 <- EJM_IRF4_binding %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  labs(x = "EJM cell line", y = "Proportion", fill = "IRF4 binding") +
  scale_x_discrete(labels=c("common", "EJM", "H929", "KMS12", "MM1S"), guide = guide_axis(angle = 45)) +
  scale_fill_manual(
    values= c("lightsalmon", "darkolivegreen")) +
  main_theme() +
  coord_fixed(ratio = 3) 


final_barchart <- ggpubr::ggarrange(trial,trial2, trial3, trial4,
                  common.legend = T, # COMMON LEGEND
                  legend = "top", # Align them both, horizontal and vertical
                  nrow = 2, ncol =2) 
final_barchart  
```

```{r}
filtered_data <- data_for_barchart %>%
  filter(category == "common" | (category == cell_line))

barchart_filtered <- filtered_data %>%
  ggplot(aes(x = category, y = proportion, fill = IRF4_binding)) +
  geom_bar(width = 0.6, stat = "identity") +
  facet_wrap(~ cell_line, scales = "free_x") +
  main_theme()
```

New IRF4 plot 
```{r}
IRF4_EJM <- enhancers_IRF4 %>%
  select(21, 24) %>%
  filter(enhancer_type != "other peak" & enhancer_type != "no enhancer") %>%
  mutate(enhancer_type = case_when(
    enhancer_type == "common" ~ "common", 
    enhancer_type == "EJM" ~ "EJM", 
    .default = "other"
  )) %>%
  group_by(enhancer_type, IRF4_EJM) %>%
  summarise(n = n()) %>%
  group_by(enhancer_type) %>%
  mutate(total = sum(n)) %>%
  mutate(proportion = n/total)

IRF4_MM1S <- enhancers_IRF4 %>%
  select(21, 22) %>%
  filter(enhancer_type != "other peak" & enhancer_type != "no enhancer") %>%
  mutate(enhancer_type = case_when(
    enhancer_type == "common" ~ "common", 
    enhancer_type == "MM1S" ~ "MM1S", 
    .default = "other"
  )) %>%
  group_by(enhancer_type, IRF4_MM1S) %>%
  summarise(n = n()) %>%
  group_by(enhancer_type) %>%
  mutate(total = sum(n)) %>%
  mutate(proportion = n/total)

IRF4_H929 <- enhancers_IRF4 %>%
  select(21, 23) %>%
  filter(enhancer_type != "other peak" & enhancer_type != "no enhancer") %>%
  mutate(enhancer_type = case_when(
    enhancer_type == "common" ~ "common", 
    enhancer_type == "H929" ~ "H929", 
    .default = "other"
  )) %>%
  group_by(enhancer_type, IRF4_H929) %>%
  summarise(n = n()) %>%
  group_by(enhancer_type) %>%
  mutate(total = sum(n)) %>%
  mutate(proportion = n/total)

IRF4_KMS12 <- enhancers_IRF4 %>%
  select(21, 25) %>%
  filter(enhancer_type != "other peak" & enhancer_type != "no enhancer") %>%
  mutate(enhancer_type = case_when(
    enhancer_type == "common" ~ "common", 
    enhancer_type == "KMS12" ~ "KMS12", 
    .default = "other"
  )) %>%
  group_by(enhancer_type, IRF4_KMS12) %>%
  summarise(n = n()) %>%
  group_by(enhancer_type) %>%
  mutate(total = sum(n)) %>%
  mutate(proportion = n/total)

IRF4_KMS12_plot <- IRF4_KMS12 %>%
  ggplot(aes(x = enhancer_type, y = proportion, fill = IRF4_KMS12)) +
  geom_bar(width = 0.6, stat = "identity") +
  main_theme()

IRF4_MM1S_plot <- IRF4_MM1S %>%
    ggplot(aes(x = enhancer_type, y = proportion, fill = IRF4_MM1S)) +
  geom_bar(width = 0.6, stat = "identity") +
  main_theme()

IRF4_EJM_plot <- IRF4_EJM %>%
    ggplot(aes(x = enhancer_type, y = proportion, fill = IRF4_EJM)) +
  geom_bar(width = 0.6, stat = "identity") +
  main_theme()

IRF4_H929_plot <- IRF4_H929 %>%
    ggplot(aes(x = enhancer_type, y = proportion, fill = IRF4_H929)) +
  geom_bar(width = 0.6, stat = "identity") +
  main_theme()
```

